/*************************************************************************
 * Header file for GameTutorial - 
 * Contains bitmaps that determine appearance of sprites
 * 
 * Written by: Brandon Farmer for TinyCircuits
 * 
 * Initiated: 03/27/2017 
 * Updated: 07/05/2018
 ************************************************************************/

#include <TinyScreen.h> // Used for the color variables available on the TinyScreen+

extern const uint16_t ALPHA;

const unsigned int ballBitmap[] = {
  ALPHA, TS_16b_White, TS_16b_White, ALPHA,
  TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White,
  TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White,
  ALPHA, TS_16b_White, TS_16b_White, ALPHA
};

const unsigned int livesBitmap[] = {
  ALPHA, TS_16b_White, TS_16b_White, ALPHA, ALPHA, ALPHA, TS_16b_White, TS_16b_White, ALPHA, ALPHA, ALPHA, TS_16b_White, TS_16b_White, ALPHA, ALPHA,
  TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White, ALPHA, TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White, ALPHA, TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White, ALPHA,
  TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White, ALPHA, TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White, ALPHA, TS_16b_White, TS_16b_White, TS_16b_White, TS_16b_White, ALPHA,
  ALPHA, TS_16b_White, TS_16b_White, ALPHA, ALPHA, ALPHA, TS_16b_White, TS_16b_White, ALPHA, ALPHA, ALPHA, TS_16b_White, TS_16b_White, ALPHA, ALPHA
};

const unsigned int redBrickBitmap[] = {
  TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red,
  TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red,
  TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red,
  TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red, TS_16b_Red
};

const unsigned int greenBrickBitmap[] = {
  TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green,
  TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green,
  TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green,
  TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green, TS_16b_Green
};

const unsigned int yellowBrickBitmap[] = {
  TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow,
  TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow,
  TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow,
  TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow, TS_16b_Yellow
};

const unsigned int platformBitmap[] = {
  TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray,
  TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray, TS_16b_Gray,
  ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA,
  ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA
};

const unsigned int tinyBrickLogoBitmap[] = {
  TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray,  
  TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, 
  ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 
  TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, 
  TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray,  ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray,  ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, 
  TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, 
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, 
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA,
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA,
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA,
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA,
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA,
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA,
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, 
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, 
  ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, ALPHA, ALPHA, ALPHA, ALPHA, TS_16b_DarkGray, TS_16b_DarkGray, 
  ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 
  TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, 
  TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray, TS_16b_DarkGray,
};
